// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using salesApi.Data;

namespace salesApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("salesApi.Models.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("customerAddress");

                    b.Property<string>("customerId");

                    b.Property<string>("customerName");

                    b.Property<string>("emailAddress");

                    b.HasKey("id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("salesApi.Models.SalesTransaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("actualSalingPrice");

                    b.Property<int>("customerId");

                    b.Property<int>("productId");

                    b.Property<int>("saleDate");

                    b.Property<int>("saleTime");

                    b.Property<int>("salesId");

                    b.HasKey("id");

                    b.ToTable("SalesTransactions");
                });

            modelBuilder.Entity("salesApi.Models.product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.Property<string>("productId");

                    b.Property<string>("productName");

                    b.Property<int>("productRate");

                    b.Property<int>("quantity");

                    b.HasKey("id");

                    b.ToTable("products");
                });
#pragma warning restore 612, 618
        }
    }
}
